language: python
python:
  - "3.6"
  - "3.7"
cache: pip3
install:
  - pip3 install -r requirements.txt
  # Installing test-enviroment
  - pip3 install pytest
  - pip3 install pytest-cov
  – pip3 install flake8
  # Building and Installing the app
  - python setup.py build
  - python setup.py install
script:
  - set -e
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - py.test --cov RIXSPlot test # Run the tests and check for test coverage.
  – flake8 RIXSPlot # Flake8-Check
  - python -m RIXSPlot --help # Check if commandline will be opened.
