language: python
python:
  - "3.6"
  - "3.7"
cache: pip3
install:
  - pip3 install -r requirements.txt
  - pip3 install pytest # Installing test-enviroment
  - pip3 install pytest-cov # Installing test-enviroment
  – pip3 install flake8 # Installing test-enviroment
  - python setup.py build   # Building and Installing the app
  - python setup.py install   # Building and Installing the app
script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - py.test --cov RIXSPlot test # Run the tests and check for test coverage.
  – flake8 RIXSPlot # Flake8-Check
  - python -m RIXSPlot --help # Check if commandline will be opened.
